services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HDNET\Calendarize\:
    resource: '../Classes/*'

  HDNET\Calendarize\Listener\CalendarizeField:
    tags:
      - name: event.listener
        identifier: 'calendarizeField'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  HDNET\Calendarize\EventListener\ImportSingleIcalEventListener:
    tags:
      - name: event.listener
        identifier: 'importSingelIcal'
        event: HDNET\Calendarize\Event\ImportSingleIcalEvent

  HDNET\Calendarize\Command\CleanupCommandController:
    tags:
      - name: console.command
        command: 'calendarize:cleanup'
        schedulable: true

  HDNET\Calendarize\Command\ImportCommandController:
    tags:
      - name: console.command
        command: 'calendarize:import'
        schedulable: true

  HDNET\Calendarize\Command\ReindexCommandController:
    tags:
      - name: console.command
        command: 'calendarize:reindex'
        schedulable: true


